name: CI
on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        npm i
        npm run test

  buildAndPublish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build $ Publish
      uses: lbejiuk/adip@v1
      with:
        TOKEN: ${{secrets.token}}
        PACKAGE_REPOSITORY: 'private_pkg'

  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: buildAndPublish
    steps:
      - name: Deploy on server
        run: |
          IMAGE_VERSION=$(echo "${{ github.sha }}" | cut -c 1-12)
          SERVICE_NAME=book_themarkz_com_screenmaker
          curl "https://themarkz.com:9999/service/update -v -f \
            -x PUT \
            -H "_xtoken: ${{ secrets.updaterToken }} \
            -H "Content-Type: application/json" \
            -d '{"serviceName": "$SERVICE_NAME", "imageVersion": "$IMAGE_VERSION"}'
