name: CI
on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        npm ci
        npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo "${{secrets.ssh_key}}" > key
        chmod 700 key
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key -p 10101 root@themarkz.com \
        export DEPLOY_TIMESTAMP=$(date +%Y-%m-%d-%H:%M:%S); \
        mkdir -p /var/production/$DEPLOY_TIMESTAMP; \
        git clone git@github.com:lBeJIuk/markz_screenshot_maker.git /var/production/$DEPLOY_TIMESTAMP; \
        cd /var/production/$DEPLOY_TIMESTAMP; \
        npm i; \
        rm /var/screenmaker; \
        service screenmaker stop: \
        ln -s /var/production/$DEPLOY_TIMESTAMP /var/screenmaker; \
        service screenmaker start;'
        shred key -n 10  -v -z -u
